define fl = Character("Fetish Locator", color="#f90e0e", what_style="fl_text")
define flr = Character("[flr_name!t]", color="#f90e0e", what_style="fl_text")
define mc = Character("[mcname]", color="#5480ff")
define mct = Character("[mcname]", color="#5480ff", what_prefix="({i}", what_suffix="{/i})")
define mcfl = Character("[mclogin]", color="#5480ff")
define pb = Character("Pete", color="#03ad68")
define hr = Character("Hana", color="#bc1ced")
define hrfl = Character("QueenB", color="#bc1ced")
define kb = Character("Kevin", color="#5ebb03")
define cb = Character("Chloe", color="#ddac30")
define mes = Character("Min", color="#de25ca")
define mesfl = Character("Squizzle", color="#de25ca")
define arj = Character("Amber-Rose", color="#f015a0")
define arjfl = Character("ErikaRed", color="#f015a0")
define cth = Character("CamTubeHelper", color="#f015a0")
define am = Character("Antony", color="#6822ff")
define amfl = Character("Mr.D1cky", color="#2e195b")
define sy = Character("Stacy", color="#81c18c")
define syfl = Character("SexyMinx", color="#81c18c")
define lc = Character("Lydia", color="#ed1c3e")
define pw = Character("Polly", color="#ff7dcd")
define nk = Character("Nora", color="#e6cffa")
define zw = Character("Zarah Waller", color="#edc31c")
define rn = Character("Ronald Nordin", color="#b3ccf2")
define dr = Character("Dario", color="#b3ccf2")
define mk = Character("Maria", color="#b50e38")
define mkfl = Character("Vesna", color="#b50e38")
define zo = Character("Zach", color="#b3ccf2")
define dd = Character("Daisy", color="#bf8506")
define dw = Character("Dahlia", color="#a10028")
define aw = Character("Allison", color="#fa2557")
define mh = Character("Lyssa", color="#945cff")
define tm = Character("Talia", color="#a32d49")
define cl = Character("Cynthia", color="#54b25a")
define js = Character("Jerome", color="#374980")
define tr = Character("Terrell", color="#00c17f")
define trfl = Character("HairyHarry", color="#1b471e")
define vw = Character("Vanessa Webb", color="#d56b85")
define jf = Character("Jessie", color="#4a99ed")
define jfx = Character("Girl", color="#326ba8")
define jffl = Character("URLittlePony", color="#326ba8")
define sa = Character("Shontae", color="#b12120")
define ceo = Character("Mr. Melville", color="#9f0300")
define jdg = Character("Judge", color="#ffffff")
define peon = Character("Woman", color="#fb9694")
define op = Character("Oliver", color="#f56e56")
define sb = Character("Samiya", color="#e0a800")
define ir = Character("Iona", color="#9fc9f9")
define irfl = Character("SuperNova", color="#9fc9f9")
define nr = Character("[nr_name!t]", color="#a5fe7e")
define ah = Character("Aaleyah", color="#d64a32")
define tl = Character("Theresa Lewald", color="#c46c93")
define cf = Character("Claudie Fulton", color="#ffffff")
define ts = Character("Tracey", color="#beaa99")
define kv = Character("Kanya", color="#1fa281")
define mys = Character("Victor Yates Jr.", color="#ffffff")
define ns = Character("Nari", color="#adadb6")
define md = Character("Mr. Min", color="#a2423a")
define mm = Character("Mrs. Min", color="#de7953")
define mb = Character("Min Do-yun", color="#b2bd97")
define vumc = Character("Officer Cheney", color="#698dbd")
define pm = Character("Officer Martinez", color = "#1a39bb")
define ac = Character("Ashley", color = "#ffa59d")
define fc = Character("Frank", color = "#b9c970")
define hh = Character("Ms. Havisham", color = "#eb4435")
define ap = Character("Alexander", color = "#9d7342")
define atp = Character("Angela", color = "#f6cd89")
define dn = Character("Dorothy", color = "#cac4c1")
define ms = Character("Mikaela", color = "#ff9966")
define dc = Character("Debbie", color = "#d4a16b")
define gt = Character("Gemma", color = "#ffffff")
define hf = Character("Harry", color = "#ffffff")
define ly = Character("Lily", color="#eb9b3b")
define rs = Character("Room Service", color="#e7dbce")
define gb = Character("Domina", color="#000000" , who_style = "dark_character" )
define jd = Character("Janet", color="#b73b26")


define sm = Character("Silvia"          , color = "#6e50c3" , who_style = "dark_character" )
define zp = Character("Zemfira"         , color = "#aa0323" , who_style = "dark_character" )
define jh = Character("Josie"           , color = "#d07318" )
define lw = Character("Lara"            , color = "#750762" , who_style = "dark_character" )
define dk = Character("Delphia"         , color = "#c32a67" )
define edo = Character("Ezra"            , color = "#889685" )

style dark_character:
    properties gui.text_properties("name", accent=True)
    xalign gui.name_xalign
    yalign 0.5
    outlines [(1, "#e1e1e1", 0, 0)]
    kerning 1
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
